# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define "db" do |db|
		db.vm.box = "VProfirov_SoftUni/centos-stream-customized"
		db.vm.box_version = "0.2"
		db.vm.hostname = "db"
		db.vm.network "private_network", ip:"192.168.99.100"
		db.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
		end
		# OR WITH A : provision shell 
		db.vm.provision "file" source: "./.vagrant-provision.cfg", destination:"/.vagrant-provision.cfg"
		db.vm.synced_folder "vagrant-share/" "/vagrant-share/"
	end
	config.vm.define "web" do |web|
		web.vm.box = "VProfirov_SoftUni/centos-stream-customized"
		web.vm.box_version = "0.2"
		web.vm.hostname = "bo"
		web.vm.network "private_network", ip:"192.168.99.101"
		web.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
		end
	end
end