---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache server
      zypper: service=apache2 state=present

    - name: Start and Enable Apache server
      service: name=apache2 state=reloaded enabled=true

    - name: Allow Apache connection through Firewall
      firewalld: service=apache2 enabled=true permanent=true immediate=true

    # - name: Add pots for Apache (default(80)-root-lvl and non-default(8080))
    #   firewalld:  port=80/tcp port=8080/tcp permanent=true immediate=true

...