
# -*- mode: ruby -*-
# vi: set ft=ruby:

Vagrant.configure("2") do |config|
	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

		# config.ssh.insert_key = false
		# config.ssh.username = "vagrant"
		# config.ssh.password = "vagrant"

	config.vm.define "centOS" do |centOS|
		centOS.vm.provider :virtualbox do |vb|
			vb.memory = "2048"
			vb.name = "centOS-big"
		end

		centOS.vm.box = "VProfirov/centos-stream-customized-big"
		centOS.vm.box_version = "0.1"

		# centOS.ssh.username = "vagrant"
		# centOS.ssh.password = "vagrant"
		# centOS.ssh.insert_key = false

		# this happens if-&-after vagrant manages to "vagrant ssh" in for a 2st time
		## current-status: fails
		centOS.vm.network :private_network, ip:"192.168.99.110"
		centOS.vm.network :forwarded_port, host:12122, guest:22

		centOS.vm.hostname = "centOS-updated"
		centOS.vm.provision :shell, privileged:true, inline: <<-EOF
		dnf update -y;
		EOF
	end
end