# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

	config.vm.define "ubuntu-updater" do |ubuntu|
		ubuntu.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			## virtualbox-machine name
			vb.name = "ubuntu-updater"
		end

		ubuntu.vm.box = "VProfirov/Ubuntu-customized"
		ubuntu.vm.box_version = "1.4"

		ubuntu.vm.hostname = "ubuntu-updater"
		ubuntu.vm.network "private_network", ip:"192.168.99.100"

		ubuntu.vm.synced_folder "vagrant/", "/vagrant"

		ubuntu.vm.provision "initial-update", type:"shell", privileged:true, inline: <<-EOF
		apt update -y
		EOF

		## FOR TESTING PURPOSE SKIP PROVISIONING :
			# ubuntu.vm.provision "bootstrap", type:"shell", path:"provisioning/ubuntu-provisioning.sh"

			# OR WITH A : provision shell
			# ubuntu.vm.provision "file" source: "./.vagrant-provision.cfg", destination:"/.vagrant-provision.cfg"

	end
end