# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true; #default(true)

	config.vm.define "openSUSE-docker" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			vb.name = "study-docker-OpenSUSE"
		end

		docker.vm.box = "VProfirov/OpenSUSE-customized"
		docker.vm.box_version = "1.4"
		docker.vm.hostname = "docker-host-OpenSUSE"
		docker.vm.network "private_network", ip:"192.168.120.23"
		docker.vm.synced_folder "vagrant/", "/vagrant"
	end
end