# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

	config.vm.define "db" do |db|
		db.vm.box = "VProfirov/OpenSUSE-customized"
		db.vm.box_version = "1.4"

		db.vm.hostname = "db"
		db.vm.network "private_network", ip:"192.168.99.100"
		db.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			vb.name = "db-OpenSUSE"
		end

		db.vm.synced_folder "./vagrant/machines/db/data-source", "/vagrant"
		db.vm.provision "bootstrap", type: "shell", path: "vagrant/machines/db/provision/OpenSUSE/db.sh"
	end
	config.vm.define "web" do |web|
		web.vm.box = "VProfirov/OpenSUSE-customized"
		web.vm.box_version = "1.4"

		web.vm.hostname = "web"
		web.vm.network "private_network", ip:"192.168.99.101"
		web.vm.network "forwarded_port", guest:80, host:8081, auto_correct: true, protocol: "tcp"
		web.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			vb.name =  "web-OpenSUSE"
		end

		web.vm.synced_folder "./vagrant/machines/web/data-source", "/vagrant"
		web.vm.provision "bootstrap", type: "shell", path: "vagrant/machines/web/provision/OpenSUSE/web.sh"
	end
end