# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true; #default(true)

	config.vm.define "openSUSE-docker-130" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "03.03.docker-host-OpenSUSE-130"
		end

		## Online repo
		# docker.vm.box = "VProfirov/OpenSUSE-customized"
		# docker.vm.box_version = "1.4"

		# ## Local repo testing
		docker.vm.box = "VProfirov/OpenSUSE-customized"
		docker.vm.box_version = "1.5"

		docker.vm.hostname = "docker-host-OpenSUSE-130"

		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2330, auto_correct: true

		docker.vm.network "private_network", ip:"192.168.99.130"
		docker.vm.network :forwarded_port, guest: 8080, host:8330, auto_correct: true
		docker.vm.synced_folder "vagrant/", "/vagrant"

		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-OpenSUSE.sh"
	end

	config.vm.define "openSUSE-docker-131" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "03.03.study-docker-OpenSUSE-131"
		end

		## Online repo
		# docker.vm.box = "VProfirov/OpenSUSE-customized"
		# docker.vm.box_version = "1.4"

		# ## Local repo testing
		docker.vm.box = "VProfirov/OpenSUSE-customized"
		docker.vm.box_version = "1.5"

		docker.vm.hostname = "docker-host-OpenSUSE-131"

		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2331, auto_correct: true

		docker.vm.network "private_network", ip:"192.168.99.131"
		docker.vm.network :forwarded_port, guest: 8080, host:8331, auto_correct: true
		docker.vm.synced_folder "vagrant/", "/vagrant"

		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-OpenSUSE.sh"
	end

	config.vm.define "openSUSE-docker-132" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "03.03.docker-host-OpenSUSE-132"
		end

		## Online repo
		# docker.vm.box = "VProfirov/OpenSUSE-customized"
		# docker.vm.box_version = "1.4"

		# ## Local repo testing
		docker.vm.box = "VProfirov/OpenSUSE-customized"
		docker.vm.box_version = "1.5"

		docker.vm.hostname = "docker-host-OpenSUSE-132"

		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2332, auto_correct: true

		docker.vm.network "private_network", ip:"192.168.99.132"
		docker.vm.network :forwarded_port, guest: 8080, host:8332, auto_correct: true
		docker.vm.synced_folder "vagrant/", "/vagrant"

		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-OpenSUSE.sh"
	end

end
