# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

	#config.vm.box_download_{,,...} checksums for the downloaded update-content

	config.vm.define "centOS" do |centOS|
		centOS.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			vb.name = "CentOS-Containerization-with-Docker"
		end

			# centOS.ssh.username = "vagrant"
			# centOS.ssh.password = "vagrant"
			# centOS.ssh.insert_key = false

		centOS.vm.box = "VProfirov/centos-stream-customized"
		centOS.vm.box_version = "0.2"
		centOS.vm.hostname = "docker-host"
		centOS.vm.network "private_network", ip:"192.168.120.10"

		centOS.vm.synced_folder "vagrant/", "/vagrant"
	end
end