# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = false; #default(true)

	#config.vm.box_download_{,,...} checksums for the downloaded update-content

	config.vm.define "docker-centOS" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			vb.name = "CentOS-Containerization-with-Docker"
		end
			# docker.ssh.username = "vagrant"
			# docker.ssh.password = "vagrant"
			# docker.ssh.insert_key = false
		docker.vm.box = "VProfirov/CentOS-Stream-08-customized"
		docker.vm.box_version = "1.1"

		docker.vm.hostname = "docker-host"
		docker.vm.network "private_network", ip:"193.168.120.10"

		docker.vm.synced_folder "vagrant/", "/vagrant"
	end
end