# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.boot_timeout = 50;
	config.vm.box_check_update = true;

	config.vm.define "ubuntu-ansible" do |ansible|
		ansible.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "ubuntu-ansible"
		end
		ansible.vm.box = "VProfirov/Ubuntu-customized"
		ansible.vm.box_version = ">= 1.4"

		ansible.vm.hostname = "ubuntu-ansible"
		ansible.vm.network :forwarded_port, id:"ssh", guest:22, host:3300, auto_correct:true
		ansible.vm.network :private_network, ip:"192.168.99.30", netmask:"255.255.255.0", auto_correct:true

		ansible.vm.synced_folder "vagrant/", "/vagrant"
		ansible.vm.provision "initial update", type:"shell", privileged:true, inline:<<-SHELL
			apt-get update
			apt-get upgrade -y
			omz update
			zplug update
			SHELL
	end

		config.vm.define "ubuntu-basic-latest" do |ubuntu|
		ubuntu.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "ubuntu-basic-latest"
		end
		ubuntu.vm.box = "VProfirov/Ubuntu-customized"
		ubuntu.vm.box_version = ">= 1.4"

		ubuntu.vm.hostname = "ubuntu-basic"
		ubuntu.vm.network :forwarded_port, id: "ssh", guest:22, host:3301, auto_correct: true
		ubuntu.vm.network :private_network, ip:"192.168.99.31", netmask:"255.255.255.0", auto_correct: true
		ubuntu.vm.network :forwarded_port, id:"http", guest:80, host:8331, auto_correct: true
		ubuntu.vm.network :forwarded_port, id:"http2", guest:8080, host:8332, auto_correct: true
		ubuntu.vm.network :forwarded_port, id:"https", guest:443, host:8333, auto_correct: true

		ubuntu.vm.synced_folder "vagrant", "/vagrant"

		ubuntu.vm.provision "initial-update", type:"shell", privileged:true, inline: <<-EOF
		apt update -y; omz update; zplug update;
		EOF
	end
end
