# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 50; #default(300)
	config.vm.box_check_update = true; #default(true)

	#config.vm.box_download_{,,...} checksums for the downloaded update-content

	config.vm.define "centOS-docker-110" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "03.01.docker-host-CentOS-110"
		end
		## ONLINE REPO
		docker.vm.box = "VProfirov/CentOS-Stream-08-customized"
		docker.vm.box_version = "1.4"
		## LOCAL REPO:LATEST
		# docker.vm.box = "CentOS-Stream-08-customized-1.4.1"
		# docker.vm.box_version = "0"

		docker.vm.hostname = "03.01.docker-host-CentOS-110"

		## the idea is to override the default Vagrant port-substitution during re/init (vagrant up)
		# current ports on the vm : host: 2201, guest:22

		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2310, auto_correct: true
		# docker.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2100, auto_correct: true

		docker.vm.network "private_network", ip:"192.168.99.110"
		# docker.vm.network :private_network, ip:"192.168.99.100"

		docker.vm.network :forwarded_port, guest: 8080, host:8310, auto_correct: true

		docker.vm.synced_folder "vagrant/", "/vagrant"

		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-CentOS.sh"
	end
	config.vm.define "centOS-docker-111" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "03.01.docker-host-CentOS-111"
		end
		## ONLINE REPO
		docker.vm.box = "VProfirov/CentOS-Stream-08-customized"
		docker.vm.box_version = "1.4"
		## LOCAL REPO:LATEST
		# docker.vm.box = "CentOS-Stream-08-customized-1.4.1"
		# docker.vm.box_version = "0"

		docker.vm.hostname = "03.01.docker-host-CentOS-111"

		## the idea is to override the default Vagrant port-substitution during re/init (vagrant up)
		# current ports on the vm : host: 2201, guest:22

		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2311, auto_correct: true
		# docker.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2100, auto_correct: true

		docker.vm.network "private_network", ip:"192.168.99.111"
		# docker.vm.network :private_network, ip:"192.168.99.100"

		docker.vm.network :forwarded_port, guest: 8080, host:8311, auto_correct: true

		docker.vm.synced_folder "vagrant/", "/vagrant"

		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-CentOS.sh"
	end
	config.vm.define "centOS-docker-112" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "03.01.docker-host-CentOS-112"
		end
		## ONLINE REPO
		docker.vm.box = "VProfirov/CentOS-Stream-08-customized"
		docker.vm.box_version = "1.4"
		## LOCAL REPO:LATEST
		# docker.vm.box = "CentOS-Stream-08-customized-1.4.1"
		# docker.vm.box_version = "0"

		docker.vm.hostname = "03.01.docker-host-CentOS-112"

		## the idea is to override the default Vagrant port-substitution during re/init (vagrant up)
		# current ports on the vm : host: 2201, guest:22

		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2312, auto_correct: true
		# docker.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2100, auto_correct: true

		docker.vm.network "private_network", ip:"192.168.99.112"
		# docker.vm.network :private_network, ip:"192.168.99.100"

		docker.vm.network :forwarded_port, guest: 8080, host:8312, auto_correct: true

		docker.vm.synced_folder "vagrant/", "/vagrant"

		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-CentOS.sh"
	end
end
