# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

	#config.vm.box_download_{,,...} checksums for the downloaded update-content

	config.vm.define "centOS" do |centOS|
		centOS.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			## virtualbox-machine name
			vb.name = "CentOS-updater"
		end

		centOS.vm.box = "VProfirov/CentOS-stream-8-minimal-customized"
		centOS.vm.box_version = "0.2"
		centOS.vm.hostname = "centOS"
		centOS.vm.network "private_network", ip:"192.168.99.100"

			# centOS.vm.synced_folder "vagrant/machines/centOS/data-source", "/vagrant/centOS"
			# centOS.vm.synced_folder "vagrant/machines/centOS/data-source", "/vagr		centOS.vm.synced_folder "vagrant/provisioning/", "/vagrant"
			# centOS.vm.provision "bootstrap", type: "shell", path: "vagrant/machines/centOS/provision/CentOS/centOS.sh"


		##centOS.vm.provision "shell", path: "provisioning/centOS.sh"
		centOS.vm.provision "shell", privileged:true, inline: <<-EOF
		dnf update -y;
 		EOF
		## shell provisioning:

		## update zsh :
		# zplug update;
		# omz update;

		# OR WITH A : provision shell
		# centOS.vm.provision "file" source: "./.vagrant-provision.cfg", destination:"/.vagrant-provision.cfg"

	end
end