# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 300; #default(300) # cheged to 100
	config.vm.box_check_update = true; #default(true)

	config.vm.define "ubuntu-docker-120" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1
      "
            vb.name = "03.02.docker-host-Ubuntu-120"
		end

		docker.vm.box = "VProfirov/Ubuntu-customized"
		docker.vm.box_version = "1.4"
		docker.vm.hostname = "docker-host-Ubuntu-120"

		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2320, auto_correct: true

		docker.vm.network "private_network", ip:"192.168.99.120"
		docker.vm.network :forwarded_port, guest: 8080, host:8320, auto_correct: true

		docker.vm.synced_folder "vagrant/", "/vagrant"

		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-Ubuntu.sh"
	end
end
