# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

	config.vm.define "openSUSE-updater" do |openSUSE|
		openSUSE.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			vb.name = "openSUSE-updater"
		end

		openSUSE.vm.box = "VProfirov/OpenSUSE-customized"
		openSUSE.vm.box_version = "1.4"

		openSUSE.vm.hostname = "openSUSE-updater"
		openSUSE.vm.network "private_network", ip:"192.168.99.103"

		openSUSE.vm.synced_folder "vagrant/", "/vagrant"

		openSUSE.vm.provision "initial-update", type:"shell", privileged:true, inline: <<-EOF
		zypper update
		EOF

		## OPENSUSE15.3 UPDATE FIX:

		# openSUSE.vm.provision "update-fix-opensuse15.3", type:"shell", privileged:true, inline: <<-EOF
		# zypper addrepo https://download.opensuse.org/repositories/home:arachnos/openSUSE_Leap_15.3/home:arachnos.repo
		# zypper refresh
		# zypper install python-iniconfig
		# zypper update
		# EOF



		## FOR TESTING PURPOSE SKIP PROVISIONING :
			# openSUSE.vm.provision "bootstrap", type:"shell", path:"provisioning/OpenSUSE-provisioning.sh"

			# OR WITH A : provision shell
			# openSUSE.vm.provision "file" source: "./.vagrant-provision.cfg", destination:"/.vagrant-provision.cfg"

	end
end