# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "hashicorp/bionic64"
	config.vm.box_check_update = false

	config.vm.network "forwarded_port", guest:80, host:61080
	# Vagrant's default ssh configuration is:
	# ssh | tcp | 127.0.0.1 | 22XX (2222 or 2200,...) | $guest_ip-default_vbox | 22


	# LOCAL ACCESS ONLY OPTION (don't use, but test == DUBT)
	#config.vm.network "forwarded_port", guest:22, host:61022, host_ip, bridge: "enp59s0-TP-Link-AX10":"127.0.0.1"
	# Private network -  host-only access to the machine #DUBT
	config.vm.network "private_network", ip:"192.168.122.100"

	# PUBLIC NETWORK FOR THE vagrant box
	# NB! boxes are insecure by default, so further reading on how-to-secure is needed
	# config.vm.network "public_network", bridge: XXXX

	# SYNCED DIRECTORY between host and guest
	config.vm.synced_folder "./shared_dir","/home/vagrant/vagrant_shared_dir"

	# PROVIDER (Virtualbox) SPECIFIC CONFIG:
	config.vm.provider "virtualbox" do |vb|
		vb.gui = true
		vb.memory = "1024" 
	end

	# EXTERNAL TOOL'S ( SHELL, Ansible, Chef, Docker, ..) PROVISIONING:
	# config.vm.provision "shell", inline: <<- SHELL
	# 	apt-get update
	# 	apt-get install -y apache2

	# 	# For Fedora:
	# 	# dnf update -y
	# 	# dnf install -y httpd
	# 	# httpd == apache2 # in CentOS/Fedora vs Debian/Ubuntu/OpenSUSE
	# SHELL
	config.vm.provision "shell",
  inline: "
		apt-get update
		apt-get install -y apache2
    "
		# For Fedora:
		# dnf update -y
		# dnf install -y httpd
    # httpd == apache2 # in CentOS/Fedora vs Debian/Ubuntu/OpenSUSE

end

