# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true; #default(true)

	config.vm.define "openSUSE-ansible-140" do |ansible|
		ansible.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "ansible-host-OpenSUSE-140"
		end

		ansible.vm.box = "VProfirov/OpenSUSE-customized"
		ansible.vm.box_version = "1.5"

		ansible.vm.hostname = "ansible-host-OpenSUSE-140"

		ansible.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2430, auto_correct: true

		ansible.vm.network "private_network", ip:"192.168.99.140"
		ansible.vm.network :forwarded_port, guest: 8080, host:8430, auto_correct: true
		ansible.vm.synced_folder "vagrant/", "/vagrant"

		ansible.vm.provision "initialize-ansible", type: "shell", privileged:true, path:"vagrant/provision/ansible-provision-OpenSUSE.sh"
	end

	config.vm.define "openSUSE-docker-141" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = "1"
			vb.name = "docker-host-OpenSUSE-141"
		end

		docker.vm.box = "VProfirov/OpenSUSE-customized"
		docker.vm.box_version = "1.5"
		
		docker.vm.hostname = "docker-host-OpenSUSE-141"
		
		docker.vm.network "private_network", ip:"192.168.99.141"
		docker.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2431, auto_correct: true
		docker.vm.network :forwarded_port, guest: 8080, host:8431, auto_correct: true
		docker.vm.synced_folder "vagrant/", "/vagrant"
		docker.vm.provision "initialize-docker", type: "shell", privileged:true, path:"vagrant/provision/docker-provision-OpenSUSE.sh"

	end
end
