# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true; #default(true)

	config.vm.define "centOS-docker" do |docker|
		docker.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = "2"
			vb.name = "study-docker-CentOS"
		end

		docker.vm.box = "VProfirov/CentOS-Stream-08-customized"
		docker.vm.box_version = "1.4"
		docker.vm.hostname = "docker-host-CentOS"
		docker.vm.network "private_network", ip:"192.168.120.21"
		docker.vm.synced_folder "vagrant/", "/vagrant"
	end
end