# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

	#config.vm.box_download_{,,...} checksums for the downloaded update-content

	# Linux OS Distro: CentOS Stream 08
	config.vm.define "db" do |db|
		db.vm.box = "VProfirov/CentOS-Stream-08-minimal-customized"
  		db.vm.box_version = "1.0"

		db.vm.hostname = "db"
		db.vm.network "private_network", ip:"192.168.99.100"
		db.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
		end
		# OR WITH A : provision shell
		# db.vm.provision "file" source: "./.vagrant-provision.cfg", destination:"/.vagrant-provision.cfg"

		# db.vm.synced_folder "vagrant/machines/db/data-source", "/vagrant/db"
		db.vm.synced_folder "vagrant/machines/db/data-source", "/vagrant/db/data-source"
		db.vm.provision "bootstrap", type: "shell", path: "vagrant/machines/db/provision/CentOS/db.sh"
	end
	config.vm.define "web" do |web|
		web.vm.box = "VProfirov/CentOS-Stream-08-minimal-customized"
  		web.vm.box_version = "1.0"

		web.vm.hostname = "web"
		web.vm.network "private_network", ip:"192.168.99.101"
		# vagrant does port-autocorrection automatically, BUT the :auto_correct option/property must be set always manually
		web.vm.network "forwarded_port", guest:80, host:8081, auto_correct: true, protocol: "tcp"
		# For the public side of the app
		# web.vm.usable_port_range = "8000..8999"
		web.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
		end

		# web.vm.synced_folder "vagrant/machines/web/data-source", "/vagrant/web"
		web.vm.synced_folder "vagrant/machines/web/data-source", "/vagrant"
		web.vm.provision "bootstrap", type: "shell", path: "vagrant/machines/web/provision/CentOS/web.sh"
	end
end