
# -*- mode: ruby -*-
# vi: set ft=ruby:

Vagrant.configure("2") do |config|
	config.vm.boot_timeout = 100; #default(300)
	config.vm.box_check_update = true #default(true)

	# config.vm.define "withBase" do |withBase|
	# 	withBase.vm.provider :virtualbox do |vb|
	# 		vb.memory = "2048"
	# 		vb.name = "withBase"
	# 	end

	# 	withBase.vm.box = "packaged-WITH-base-option"
	# 	# withBase.vm.box_version = "0.1"

	# 	withBase.vm.network :private_network, ip:"192.168.50.101"

	# 	withBase.vm.hostname = "withBase"
	# 	# withBase.vm.provision :shell, privileged:true, inline: <<-EOF
	# 	# echo "hi from withBase"
	# 	# EOF
	# end

	# config.vm.define "without" do |without|
	# 	without.vm.provider :virtualbox do |vb|
	# 		vb.memory = "2048"
	# 		vb.name = "without-Base"
	# 	end

	# 	without.vm.box = "packaged-without-base-option"
	# 	# withBase.vm.box_version = "0.1"

	# 	without.vm.network :private_network, ip:"192.168.50.102"

	# 	without.vm.hostname = "WITHOUTbase"
	# 	# without.vm.provision :shell, privileged:true, inline: <<-EOF
	# 	# echo "hi from WITHOUT-BASE"
	# 	# EOF
	# end

	config.vm.define "repackaged" do |repackaged|
		repackaged.vm.provider :virtualbox do |vb|
			vb.memory = "2048"
			vb.name = "repackaged-box"
		end

		repackaged.vm.box = "packaged-with-REPACAKGE-option"
		# withBase.vm.box_version = "0.1"

		repackaged.vm.network :private_network, ip:"192.168.50.103"

		repackaged.vm.hostname = "repackaged"
		# without.vm.provision :shell, privileged:true, inline: <<-EOF
		# echo "hi from WITHOUT-BASE"
		# EOF
	end
end